[package]
name = "sketch-oxide-java"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
jni.workspace = true
sketch_oxide = { path = "../sketch_oxide" }

[build-dependencies]

[lib]
crate-type = ["cdylib"]
